# Generated by Django 4.2.3 on 2024-09-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='static/img/avatars/'),
        ),
    ]
