# Generated by Django 4.2.3 on 2024-09-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(default='static/img/avatars/defaultPusheen.png', upload_to='static/img/avatars/'),
        ),
    ]
