# Generated by Django 4.2.3 on 2024-09-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_api_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
