# Generated by Django 4.2.3 on 2024-09-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='score_pong',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
