# Generated by Django 4.2.3 on 2024-09-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_friendrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_active',
        ),
    ]
