# Generated by Django 4.2.3 on 2024-10-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_customuser_score_pong'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
