# Generated by Django 4.2.3 on 2024-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_friendrequest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
