# Generated by Django 4.2.3 on 2024-10-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_customuser_active_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='score_pong',
        ),
    ]
