# Generated by Django 4.2.3 on 2024-11-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_customuser_score_pong'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='channel_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
