# Generated by Django 4.2.3 on 2024-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_customuser_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='channel_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
